import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'
import Provider from '../components/Provider/Provider'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog List',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container">
          <Provider>
            <Navbar isAdmin={session?.user.isAdmin || false} />
            {children}
          </Provider>
        </div>
      </body>
    </html>
  )
}